Algoritmo "semnome"

Var

   a, b, c, quadrado, trapezio, triangulo: real

Inicio

       escreva("Digite a medida A: ")
       leia(a)
       escreva("Digite a medida B: ")
       leia(b)
       escreva("Digite a medida C: ")
       leia(c)
       quadrado <- a * a
       triangulo <- (a * b)/2
       trapezio <- ((a + b)* c)/2
       
       escreval("AREA DO QUADRADO = ",quadrado)
       escreval("AREA DO TRIANGULO = ",triangulo)
       escreval("AREA DO TRAPÉZIO = ",trapezio)
Fimalgoritmo